
FROM quay.io/oauth2-proxy/oauth2-proxy

COPY oauth2-proxy.cfg .

USER root

RUN apk --no-cache add curl

ARG OPENVSCODE_HOSTPORT

ENV OAUTH2_PROXY_UPSTREAMS="http://${OPENVSCODE_HOSTPORT}"

ENTRYPOINT ["/bin/oauth2-proxy", "--config=./oauth2-proxy.cfg"]
